version: "3.8"
services:

  mongo-db:
    image: mongo
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    container_name: mongo-db
    volumes:
      - ./db/:/data/db
    networks:
      - proxy-network

  gateway:
    build:
      context: ../gateway
      target: production
    restart: always
    env_file: .env
    ports:
      # - ${REACT_APP_GATEWAY_PORT}:${REACT_APP_GATEWAY_PORT}
      - 3000:3000
    volumes:
      - ../gateway:/app
    stdin_open: true
    tty: true
    networks:
      - proxy-network

  server:
    depends_on:
      - mongo-db
    build:
      context: ../server
      target: production
    restart: always
    env_file: .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ../server:/app
    stdin_open: true
    tty: true
    links:
      - mongo-db
    networks:
      - proxy-network

  client:
    depends_on:
      - server
    build:
      context: ../client
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    ports:
      - "8080:8080"
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - ../client:/app
    stdin_open: true
    tty: true
    profiles:
      - "production"

  client-dev:
    depends_on:
      - server
    build:
      context: ../client
      dockerfile: Dockerfile.dev
      target: dev
    restart: always
    env_file: .env
    ports:
      - "8080:8080"
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - ../client:/app
    stdin_open: true
    tty: true
    profiles:
      - "dev"

networks:
  proxy-network:
    name: custom_network
